
-- Full PostgreSQL schema for Attendance Portal (RDS compatible)

SET client_encoding = 'UTF8';
SET standard_conforming_strings = 'on';
SELECT pg_catalog.set_config('search_path', 'public', false);

-- ANNOUNCEMENT
CREATE SEQUENCE public.announcement_id_seq AS integer START WITH 1 INCREMENT BY 1;
CREATE TABLE public.announcement (
    id integer NOT NULL DEFAULT nextval('public.announcement_id_seq'::regclass),
    title varchar(255),
    description text,
    created_by integer,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    message text NOT NULL,
    target_role varchar(255) NOT NULL,
    PRIMARY KEY (id)
);

-- ATTENDANCE
CREATE SEQUENCE public.attendance_id_seq AS integer START 1 INCREMENT 1;
CREATE TABLE public.attendance (
    id integer NOT NULL DEFAULT nextval('public.attendance_id_seq'::regclass),
    user_id integer NOT NULL,
    date date NOT NULL,
    status varchar(255),
    login_time time(6),
    logout_time time(6),
    remarks varchar(255),
    marked_by integer,
    updated_at timestamp(6) with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY (id)
);

-- ATTENDANCE_RECORDS
CREATE TABLE public.attendance_records (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    date varchar(255),
    domain varchar(255),
    empid varchar(255),
    name varchar(255),
    status varchar(255),
    PRIMARY KEY (id)
);

-- CSV_FILES
CREATE TABLE public.csv_files (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    file_data bytea NOT NULL,
    PRIMARY KEY (id)
);

-- HOLIDAY
CREATE SEQUENCE public.holiday_seq START 1 INCREMENT 50;
CREATE TABLE public.holiday (
    id integer NOT NULL DEFAULT nextval('public.holiday_seq'::regclass),
    created_at timestamp(6) with time zone NOT NULL,
    date date NOT NULL,
    description text,
    name varchar(255) NOT NULL,
    PRIMARY KEY (id)
);

-- LEAVE REQUEST
CREATE SEQUENCE public.leave_request_id_seq START 1 INCREMENT 1;
CREATE TABLE public.leave_request (
    id integer NOT NULL DEFAULT nextval('public.leave_request_id_seq'::regclass),
    user_id integer NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    reason text NOT NULL,
    status varchar(255) NOT NULL,
    approval_date timestamp with time zone,
    approved_by integer,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    attachment_url text,
    pending_leaves integer,
    used_leaves integer,
    PRIMARY KEY (id)
);

-- PAYSLIP
CREATE SEQUENCE public.payslip_id_seq START 1 INCREMENT 1;
CREATE TABLE public.payslip (
    id integer NOT NULL DEFAULT nextval('public.payslip_id_seq'::regclass),
    empid varchar(255),
    full_name varchar(255),
    month integer,
    year integer,
    file_name varchar(255),
    uploaded_on date,
    cloudinary_public_id varchar(255),
    cloudinary_url varchar(255),
    PRIMARY KEY (id)
);

-- PERFORMANCE
CREATE SEQUENCE public.performance_id_seq START 1 INCREMENT 1;
CREATE TABLE public.performance (
    id integer NOT NULL DEFAULT nextval('public.performance_id_seq'::regclass),
    user_id integer NOT NULL,
    reviewed_by integer,
    rating integer,
    comments text,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

-- PERFORMANCE REVIEW
CREATE SEQUENCE public.performance_review_seq START 1 INCREMENT 50;
CREATE TABLE public.performance_review (
    id integer NOT NULL DEFAULT nextval('public.performance_review_seq'::regclass),
    behavior_score double precision NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    feedback text,
    month integer NOT NULL,
    rating double precision NOT NULL,
    task_completion double precision NOT NULL,
    updated_at timestamp(6) with time zone,
    week_number integer NOT NULL,
    year integer NOT NULL,
    reviewed_by integer,
    user_id integer NOT NULL,
    PRIMARY KEY (id)
);

-- SALARY
CREATE SEQUENCE public.salary_seq START 1 INCREMENT 50;
CREATE TABLE public.salary (
    id integer NOT NULL DEFAULT nextval('public.salary_seq'::regclass),
    current_month_earned double precision NOT NULL,
    daily_rate double precision NOT NULL,
    deduction double precision,
    last_updated timestamp(6) with time zone,
    monthly_salary double precision NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (id)
);

-- USERS
CREATE SEQUENCE public.users_id_seq START 1 INCREMENT 1;
CREATE TABLE public.users (
    id integer NOT NULL DEFAULT nextval('public.users_id_seq'::regclass),
    email varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    full_name varchar(255),
    role varchar(255),
    empid varchar(255),
    phone varchar(255),
    dob varchar(255),
    address1 varchar(255),
    address2 varchar(255),
    city varchar(255),
    state varchar(255),
    country varchar(255),
    pincode varchar(255),
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
    domain varchar(255),
    designation varchar(255),
    base_salary double precision,
    photo_url varchar(255),
    department varchar(255),
    joining_date varchar(255),
    date_of_birth date,
    monthly_salary integer,
    PRIMARY KEY (id)
);

-- WALLET
CREATE SEQUENCE public.wallet_id_seq START 1 INCREMENT 1;
CREATE TABLE public.wallet (
    id integer NOT NULL DEFAULT nextval('public.wallet_id_seq'::regclass),
    user_id integer NOT NULL,
    amount numeric(10,2) DEFAULT 0,
    transaction_type varchar(20),
    description text,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
